# Generated by Django 6.1.1 on 2026-10-07 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0012_chatattachmentdeletion_chatattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.BigAutoField(primary_key=True, serialize=False)),
                ('accepted_payload', models.JSONField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(db_index=True, default='queued', max_length=24)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('attempt', models.UUIDField(null=True)),
                ('human_id', models.UUIDField(default=uuid.uuid4)),
                ('answer_id', models.UUIDField(default=uuid.uuid4)),
                ('worker', models.JSONField(default=dict)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='llm.usagecharge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='llm.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=16)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='llm.chatrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['request', 'id'], name='chat_request_event_cursor')],
            },
        ),
    ]
