# Generated by Django 6.1.1 on 2026-10-08 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0009_stadium_guides'),
        ('llm', '0013_merge_attachment_and_legacy_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightVideo',
            fields=[
                ('video_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('game_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseball.team')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseball.game')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseball.team')),
            ],
        ),
        migrations.CreateModel(
            name='HighlightScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sec', models.IntegerField()),
                ('end_sec', models.IntegerField(blank=True, null=True)),
                ('inning', models.SmallIntegerField(blank=True, null=True)),
                ('half', models.CharField(blank=True, max_length=2)),
                ('batter_name', models.CharField(blank=True, max_length=80)),
                ('pitcher_name', models.CharField(blank=True, max_length=80)),
                ('event', models.CharField(max_length=16)),
                ('rbi', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('batter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseball.player')),
                ('batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='baseball.team')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='llm.highlightvideo')),
            ],
            options={
                'ordering': ['video', 'start_sec'],
                'indexes': [models.Index(fields=['event'], name='highlight_scene_event'), models.Index(fields=['batter_name'], name='highlight_scene_batter')],
            },
        ),
    ]
