# Generated by Django 6.1.1 on 2026-10-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0013_chatrequest_chatrequestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='lease_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='llm.chatsession'),
        ),
    ]
